apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc 
  namespace: banking 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests: 
      storage: 50Gi