apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: banking-secrets-aws
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "banking-secrets"
        objectType: "secretsmanager"
        jmesPath: 
          - path: DB_PASSWORD
            objectAlias: DB_PASSWORD
          - path: JWT_SECRET
            objectAlias: JWT_SECRET
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: banking-service-account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::463470963000:role/banking-secrets-role