apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  labels:
    app: transaction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      serviceAccountName: banking-service-account
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfied: DoNotSchedule
        labelSelector:
          matchLabels:
            app: transaction-service 
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In 
                values: 
                - transaction-service 
            topologyKey: topology.kubernetes.io/zone
      containers:
      - name: transaction-service
        image: your-registry/transaction-service:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: banking-config
        env:
        - name: DB_PASSWORD_FILE
          value: "/mnt/secrets-store/DB_PASSWORD"
        - name: JWT_SECRET_FILE
          value: "/mnt/secrets-store/JWT_SECRET"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        volumeMounts:
          name: secrets-store
          mountPath: /mnt/secrets-store 
          readOnly: true
        volumes: 
        - name: secrets-store 
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: banking-secrets-aws
